# Generated by Django 5.1.3 on 2024-12-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id_doenca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_doenca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VAC', 'Vacinação'), ('ALI', 'Alimentação'), ('PES', 'Pesagem'), ('TRA', 'Tratamento'), ('REP', 'Reprodução'), ('OUT', 'Outro')], default='VAC', max_length=3, verbose_name='Tipo de Manejo')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_manejo', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('principio_ativo', models.CharField(blank=True, max_length=255, null=True)),
                ('dosagem', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=100, null=True)),
                ('indicacao', models.TextField(blank=True, null=True)),
                ('contraindicacoes', models.TextField(blank=True, null=True)),
                ('modo_de_uso', models.TextField(blank=True, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('estoque_atual', models.PositiveIntegerField(default=0)),
                ('unidade_medida', models.CharField(choices=[('mg', 'Miligrama'), ('ml', 'Mililitro'), ('un', 'Unidade')], default='mg', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_raca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ovino',
            fields=[
                ('id_ovino', models.AutoField(primary_key=True, serialize=False)),
                ('foto_ovino', models.ImageField(blank=True, null=True, upload_to='')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome_ovino', models.CharField(max_length=255)),
                ('sexo_ovino', models.CharField(max_length=1)),
                ('data_nasc', models.DateField()),
                ('data_cad', models.DateField()),
                ('peso_ovino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.categoria')),
                ('id_raca', models.ForeignKey(blank=True, db_column='id_raca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.raca')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id_manutencao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_manutencao', models.CharField(max_length=255)),
                ('desc_manutencao', models.TextField(null=True)),
                ('data_manutencao', models.DateField()),
                ('id_doenca', models.ForeignKey(blank=True, db_column='id_doenca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.doenca')),
                ('id_manejo', models.ForeignKey(blank=True, db_column='id_manejo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.manejo')),
                ('id_medicamento', models.ForeignKey(blank=True, db_column='id_medicamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.medicamento')),
                ('id_ovino', models.ForeignKey(blank=True, db_column='id_ovino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.ovino')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('nome_historico', models.CharField(max_length=255)),
                ('data_historico', models.CharField(max_length=20)),
                ('id_manutencao', models.ForeignKey(blank=True, db_column='id_manutencao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.manutencao')),
                ('id_ovino', models.ForeignKey(blank=True, db_column='id_ovino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ovinogestApp.ovino')),
            ],
        ),
    ]
