# Generated by Django 5.1.2 on 2024-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovinogestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovino',
            name='foto_ovino',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
